// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbFRlA4M1bDL8CSNQRofHIQ-u7Rm1wihw',
    appId: '1:436856805668:web:38a20d6acbde219a7bbbb1',
    messagingSenderId: '436856805668',
    projectId: 'sidang-6865a',
    authDomain: 'sidang-6865a.firebaseapp.com',
    databaseURL: 'https://sidang-6865a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sidang-6865a.firebasestorage.app',
    measurementId: 'G-F4T13PT7K3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChQ0WyEy_vYrqqwZPwCaSxy0Qnebu4l6M',
    appId: '1:436856805668:android:078ff97488cf926a7bbbb1',
    messagingSenderId: '436856805668',
    projectId: 'sidang-6865a',
    databaseURL: 'https://sidang-6865a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sidang-6865a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOyiGXFBg-OQPmob_h1xdJ08Tkonjs4PA',
    appId: '1:436856805668:ios:9a8dfb8029715a377bbbb1',
    messagingSenderId: '436856805668',
    projectId: 'sidang-6865a',
    databaseURL: 'https://sidang-6865a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sidang-6865a.firebasestorage.app',
    iosBundleId: 'com.example.sidangkufix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOyiGXFBg-OQPmob_h1xdJ08Tkonjs4PA',
    appId: '1:436856805668:ios:9a8dfb8029715a377bbbb1',
    messagingSenderId: '436856805668',
    projectId: 'sidang-6865a',
    databaseURL: 'https://sidang-6865a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sidang-6865a.firebasestorage.app',
    iosBundleId: 'com.example.sidangkufix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbFRlA4M1bDL8CSNQRofHIQ-u7Rm1wihw',
    appId: '1:436856805668:web:4370ca06df65383c7bbbb1',
    messagingSenderId: '436856805668',
    projectId: 'sidang-6865a',
    authDomain: 'sidang-6865a.firebaseapp.com',
    databaseURL: 'https://sidang-6865a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sidang-6865a.firebasestorage.app',
    measurementId: 'G-3Q4YWCTWC2',
  );
}
